development:
  adapter: postgresql
  database: tardis_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: tardis_test
  host: localhost
  min_messages: warning
  username: